services:
  origin:
    image: timefactory/origin:demo
    container_name: origin
    pull_policy: always
    environment:
      - TITLE=the perpetual motion machine
      - LOGO=https://zero.s3.timefactory.io/timefactory.svg
      - SLIDES=https://zero.s3.timefactory.io/slides
      - TEXT=https://raw.githubusercontent.com/timefactoryio/pathless/refs/heads/main/README.md
    ports:
      - 127.0.0.1:1000:1000
      - 127.0.0.1:1001:1001
